# Generated by Django 4.1.7 on 2023-07-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='3fa85f64-5717-4562-b3fc-2c963f66afa6', on_delete=django.db.models.deletion.CASCADE, to='core_orders.orders'),
            preserve_default=False,
        ),
    ]
