# Generated by Django 4.1.7 on 2023-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0002_remove_orders_order_items_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='cash on delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=100),
        ),
    ]
