# Generated by Django 4.1.7 on 2023-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_orders', '0003_orders_payment_method_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('khalti', 'khalti'), ('esewa', 'esewa')], default='cash on delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('un-paid', 'un-paid')], default='un-paid', max_length=100),
        ),
    ]
