# Generated by Django 4.1.7 on 2023-06-29 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Product created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Product Last updated')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['public_id', 'product_name', 'created', 'updated'], name='core_produc_public__5353b6_idx'),
        ),
    ]
