# Generated by Django 4.1.7 on 2023-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
