# Generated by Django 4.1.7 on 2023-07-12 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_product_categories', '0001_initial'),
        ('core_product', '0002_product_description_product_image_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_product_categories.productcategories'),
        ),
    ]
