# Generated by Django 4.1.7 on 2023-06-29 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Product category created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Product category last updated')),
            ],
        ),
        migrations.AddIndex(
            model_name='productcategories',
            index=models.Index(fields=['public_id', 'category_name', 'created', 'updated'], name='core_produc_public__bfbab7_idx'),
        ),
    ]
