# Generated by Django 4.1.7 on 2023-06-30 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='First Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last Updated')),
            ],
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['public_id', 'created', 'updated'], name='core_restau_public__b87e88_idx'),
        ),
    ]
