# Generated by Django 4.1.7 on 2023-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_restaurant', '0003_restaurant_address_restaurant_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='default/restautant.png', upload_to='restaurants'),
        ),
    ]
