# Generated by Django 4.1.7 on 2023-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_restaurant', '0004_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(default='10:00 AM - 9:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=30),
        ),
    ]
