# Generated by Django 4.1.7 on 2023-07-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_usermanagement', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(db_index=True, default='kathmandu,', max_length=50),
        ),
    ]
